### PR TITLE
Add new swarmplot function

### PR DESCRIPTION
**Pull request by sunroofgod**
NEW Features:
- Added new swarmplot function (with asymmetric plot functionality)
- Added new DABEST feature for choosing of asymmetric side for swarmplots via `swarm_side` in `.plot()` method

***
Bug Fixes:
- Fixed bug involving summary lines not showing up for Gardner-Altman plots
- Fixed bug involving image comparison unit tests not detecting differences in labels

### CODE REVIEW

**Comment by sangyu** [comment]
@sunroofgod nice code! I just tested it it works very well! since now this is going to be the default behaviour, please do the following: 
1.  Update the test graphics so that pytests will pass.
2. Add a section in `06-plotaesthetics.ipynb` to demonstrate the use of the `swarm-side` argument. Alternatively, since the is such a departure from regular swarm plots, maybe it can be explained in `01-basics.ipynb`

**Comment by sunroofgod** [comment]
Hi @sangyu, will do! 

I've already previously updated the images for pytest. You can see the new images under the commit that says "updated baseline images..."

With regards to the tutorial updates, I'll update them and let you know once its been done :)

**Comment by sangyu** [comment]
oh my bad I missed the baseline images. nice thanks!

**Comment by sunroofgod** [comment]
hi, I realised maybe I should only be editting the tutorial docs once I've rebased this branch on top of the new Rosa changes (because Rosa made changes to the documentation docs too). So maybe I'll only be doing this once PR https://github.com/ACCLAB/DABEST-python/pull/157 has been merged?

**Comment by sunroofgod** [comment]
@sangyu I've added a section in `06-plotaesthetics.ipynb` to demonstrate the use of the `swarm_side` argument. I also reran the notebooks to reflect the new changes for all the swarmplots & deltadots.

**Comment by sangyu** [comment]
nice thanks!

**Pull request merged**
